drop database BDFIGURINO;
CREATE DATABASE BDFIGURINO DEFAULT CHARACTER SET utf8 ; -- cria o banco de dados
SELECT * FROM USUARIO;
CREATE TABLE USUARIO(
	ID_USER INT auto_increment primary key,
    NICK VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(32) NOT NULL
);
INSERT INTO USUARIO (ID_USER, NICK, EMAIL, SENHA) VALUES 
(1, 'MariaGames','mariaduda@email.com', '123456789');